name: rxdart_switchmap_potential_bug
description: switchMap trouble
author: Alex Fallenstedt <a.fallenstedt@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  rxdart: '0.22.1'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
